#define VDIV_Pin GPIO_PIN_1
#define VDIV_GPIO_Port GPIOA
#define NTC2_Pin GPIO_PIN_2
#define NTC2_GPIO_Port GPIOA
#define NTC_Pin GPIO_PIN_3
#define NTC_GPIO_Port GPIOA
#define EncoderData_Pin GPIO_PIN_6
#define EncoderData_GPIO_Port GPIOA
#define EncoderCLK_Pin GPIO_PIN_7
#define EncoderCLK_GPIO_Port GPIOA
#define SW_Pin GPIO_PIN_0
#define SW_GPIO_Port GPIOB
#define FAN_Pin GPIO_PIN_1
#define FAN_GPIO_Port GPIOB
#define GATE_Pin GPIO_PIN_10
#define GATE_GPIO_Port GPIOA
#define SCL_Pin GPIO_PIN_6
#define SCL_GPIO_Port GPIOF
#define SDA_Pin GPIO_PIN_7
#define SDA_GPIO_Port GPIOF

